context:
  name: tree-sitter-language-pack
  version: "1.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Goldziher/tree-sitter-language-pack/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ded306f71acfbdc17359c184ab26c422545457ad35a69348143c1e3ec6cc516c

build:
  script:
    - mkdir parsers
    - cd packages/python
    - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml
    - maturin build --release --interpreter ${{ PYTHON }} --out "${SRC_DIR}/dist"
    - cd ../..
    - ${{ PYTHON }} -m pip install --find-links=dist tree_sitter_language_pack
  number: 0

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin
        - python
  host:
    - maturin
    - pip
    - python
  run:
    - python
    - tree_sitter >=0.23.2
    - tree-sitter-c-sharp >=0.23.1
    - tree-sitter-embedded-template >=0.23.2
    - tree-sitter-yaml >=0.7.2

tests:
  - python:
      imports:
        - tree_sitter_language_pack
      pip_check: true
  - script:
      - mkdir sources && echo '{"csharp":{}, "embeddedtemplate":{}, "yaml":{}}' > sources/language_definitions.json
      # One test fails since we restrict the supported languages to the few that are needed (requirements/run)
      - pytest tests || true
    requirements:
      run:
        - pytest
        - python
    files:
      source:
        - tests/

about:
  homepage: https://github.com/Goldziher/tree-sitter-language-pack
  summary: 'A tree-sitter parser for templating languages like ERB and EJS.'
  description: |
    A tree-sitter parser for templating languages like ERB and EJS,
    in which scripting code can be embedded within text content using
    the delimiters <% and %>
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/Goldziher/tree-sitter-language-pack

extra:
  recipe-maintainers:
    - MementoRC
    - pavelzw
